#!/usr/bin/env bash
water=$(echo "$WATER" | tr 'water' '01234')
stir=$(echo "$STIR" | tr 'stir.' '01234')
to_decimal() {
    awk -v num="$1" '
    BEGIN {
        base = 5
        result = 0
        for (i = 1; i <= length(num); i++) {
            digit = substr(num, i, 1)
            result = result * base + digit
        }
        print result
    }'
}
w_dec=$(to_decimal "$water")
s_dec=$(to_decimal "$stir")
sum=$((w_dec + s_dec))
to_base8() {
    awk -v num="$1" '
    BEGIN {
        if (num == 0) { print 0; exit }
        base = 8
        result = ""
        while (num > 0) {
            result = (num % base) result
            num = int(num / base)
        }
        print result
    }'
}

base8=$(to_base8 "$sum")
echo "$base8" | tr '01234567' 'bestchol'
